[package]
name = "orders"
version = "0.1.0"
authors = ["Your Name <your.name@example.com>"]

[dependencies]
nickel = "0.8.1"
rustc-serialize = "0.3.19"
r2d2 = "0.7.0"
r2d2_postgres = "0.10.1"
nickel_postgres = { git = "https://github.com/hjr3/nickel-postgres", rev = "9c1e21f" }
